### ISSUE TITLE
GPC deployment cfrashes with TypeError: Cannot read property 'method' of undefined

### ISSUE THREAD

**Issue by cloudwheels** [thodges-gh/CL-JSONRPC-EA#3]
Deployed to GPC as per instructions.

Function crashes with error:
```
TypeError: Cannot read property 'method' of undefined at createRequest (/srv/index.js:8:31) at exports.gcpservice (/srv/index.js:45:5)
```

Added debug lines to `console.log(input)` (Not sure why I can't exmine payload in gpc logs!) and it is defined as expected:
```
{ jsonrpc: '2.0', method: 'GetNetworkId', params: [ '' ], id: '278c97ffadb54a5bbb93cfec5f7b5503' }
```

**Comment by cloudwheels** [comment]
OK, I see it.
No data property in the input object.
However, function now times out (without error) attempting to read input.method

**Comment by cloudwheels** [comment]
OK, my bad, timeout due to incorrect URL and obviously posting JSON incorrectly. Sorry! Closing....
